import React, { useState } from 'react';

interface GeneratorCardProps {
  Title: string;
}

const sampleReadme = `# 📝 Generated README

## 📄 Description

This is an autogenerated README file for the project.

## ⚙️ Installation

To install the project dependencies, run the following command:

\`\`\`bash
npm install
\`\`\`
`;

const GeneratorCard: React.FC<GeneratorCardProps> = ({ Title }) => {
  const [showCanvas, setShowCanvas] = useState(true);
  const [readmeContent] = useState(sampleReadme);

  const handleGenerate = () => {
    setShowCanvas(true);
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(readmeContent);
      // alert('Copied to clipboard!');
    } catch (err) {
      // alert('Failed to copy!');
    }
  };

  const handleDownload = () => {
    const blob = new Blob([readmeContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'README.md';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col items-center w-full max-w-2xl mx-auto rounded-2xl overflow-hidden shadow-lg bg-[#0d1117]">
      
      <div className="flex justify-between items-center w-full px-4 py-2 bg-[#0d1117] border-b border-[#30363d]">
        <div className="flex items-center space-x-2">
          <img src="src/assets/logo.png" alt="GitChat Logo" className="w-8 h-8" />
          <span className="text-xl font-bold text-purple-500">GitChat</span>
        </div>
        <h1 className="text-white text-sm">{Title} Generator</h1>
      </div>

      {/* Input Section */}
      <div className="bg-[#1d2124] w-full flex flex-col justify-center items-center p-6 space-y-4">
        <h1 className="text-[#8b949e] text-2xl font-semibold">
          Enter Repository URL
        </h1>
        <input
          type="text"
          placeholder="Enter your GitHub Repo URL"
          className="border border-[#8b949e] text-white placeholder-[#8b949e] rounded-lg p-2 w-full focus:outline-none focus:ring-2 focus:ring-purple-500 bg-[#0d1117]"/>
        <button
          onClick={handleGenerate}
          className="text-white bg-purple-600 hover:bg-purple-700 transition-all duration-200 border border-purple-500 w-full py-2 rounded-lg shadow-lg font-semibold cursor-pointer">
          Generate {Title}
        </button>
      </div>

      {showCanvas && (
        <div className="bg-[#161b22] text-[#c9d1d9] w-full p-6 space-y-4 rounded-b-2xl">
          <h2 className="text-2xl font-bold">Generated README</h2>
          <pre className="bg-[#0d1117] text-white font-mono p-4 rounded whitespace-pre-wrap overflow-x-auto text-sm border border-[#30363d]">
            {readmeContent}
          </pre>
          <div className="flex flex-wrap gap-4">
            <button
              onClick={handleCopy}
              className="border border-gray-500 text-white px-4 py-2 cursor-pointer rounded hover:bg-[#21262d] transition">
              Copy to Clipboard
            </button>
            <button
              onClick={handleDownload}
              className="bg-purple-600 text-white px-4 py-2 rounded cursor-pointer hover:bg-purple-700 transition">
              Download README.md
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default GeneratorCard;
